[package]
name = "fluxnode_api_mask"
version = "1.2.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.4"
tokio-retry = "0.3"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = "0.1.9"
futures = "0.3"
axum = "0.7"
tower-http = { version = "0.6", features = ["cors"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
